"""Report assembler — combines executive summary + appendix into a self-contained HTML file (v4).

One public function: ``assemble_report()``.
"""

from __future__ import annotations

import html as html_mod
from datetime import datetime, timezone

from wxcli.migration.report.executive import generate_executive_summary
from wxcli.migration.report.appendix import generate_appendix
from wxcli.migration.report.styles import REPORT_CSS, GOOGLE_FONTS_LINKS
from wxcli.migration.store import MigrationStore


def assemble_report(
    store: MigrationStore,
    brand: str,
    prepared_by: str,
    cluster_name: str = "",
    cucm_version: str = "",
    executive_only: bool = False,
) -> str:
    """Assemble a complete, self-contained HTML assessment report.

    Args:
        store: Populated MigrationStore (post-analyze state).
        brand: Customer/brand name for the report header.
        prepared_by: Name of the SE/engineer who prepared the report.
        cluster_name: CUCM cluster name (optional).
        cucm_version: CUCM version string (optional).
        executive_only: If True, skip the technical appendix.

    Returns:
        Complete HTML document string (starts with ``<!DOCTYPE html>``).
    """
    safe_brand = html_mod.escape(brand)
    safe_prepared_by = html_mod.escape(prepared_by)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Generate executive summary HTML
    executive_html = generate_executive_summary(
        store,
        brand=brand,
        prepared_by=prepared_by,
        cluster_name=cluster_name,
        cucm_version=cucm_version,
    )

    # Generate appendix HTML (unless executive_only)
    appendix_html = ""
    if not executive_only:
        appendix_html = generate_appendix(store)

    # Build sidebar nav
    sidebar_nav = _build_sidebar_nav(executive_only)

    # IntersectionObserver script for scroll tracking
    observer_js = _intersection_observer_js()

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CUCM Migration Assessment — {safe_brand}</title>
  {GOOGLE_FONTS_LINKS}
  <style>{REPORT_CSS}</style>
</head>
<body>
  <!-- Print header (hidden on screen) -->
  <div class="print-header">
    <h1>CUCM Migration Assessment</h1>
    <p class="meta">{safe_brand} | Prepared by {safe_prepared_by} | {date_str}</p>
  </div>

  <!-- Screen header -->
  <div class="page-header">
    <div class="brand">{safe_brand}</div>
    <h1>CUCM Migration Assessment</h1>
    <div class="subtitle">Prepared by {safe_prepared_by}</div>
    <div class="meta">{date_str}</div>
  </div>

  <div class="main-layout">
    <nav class="step-list">
    {sidebar_nav}
    </nav>
    <div class="detail-panel">
      {executive_html}
      {appendix_html}
      <footer class="report-footer">
        <p>Generated by cucm-assess | {date_str}</p>
      </footer>
    </div>
  </div>

  {observer_js}
</body>
</html>"""


def _build_sidebar_nav(executive_only: bool) -> str:
    """Build the sidebar navigation HTML with numbered exec + lettered tech items."""
    exec_items = [
        ("1", "#score", "Migration Complexity"),
        ("2", "#inventory", "What You Have"),
        ("3", "#decisions", "What Needs Attention"),
        ("4", "#next-steps", "Next Steps"),
    ]

    tech_items = [
        ("A", "#objects", "Object Inventory"),
        ("B", "#decision-detail", "Decision Detail"),
        ("C", "#css-partitions", "CSS / Partitions"),
        ("D", "#device-detail", "Device Inventory"),
        ("E", "#dn-analysis", "DN Analysis"),
        ("F", "#user-device-map", "User/Device Map"),
        ("G", "#routing", "Routing Topology"),
        ("H", "#voicemail", "Voicemail Analysis"),
        ("I", "#coverage", "Data Coverage"),
        ("J", "#gateways", "Gateways & Analog Ports"),
        ("K", "#call-features", "Call Features"),
        ("L", "#button-templates", "Button Templates"),
        ("M", "#device-layouts", "Device Layouts"),
        ("N", "#softkeys", "Softkey Migration"),
    ]

    parts = [
        '<div class="step-list-section">',
        '<div class="step-list-section-title">Executive Summary</div>',
    ]
    for num, href, label in exec_items:
        parts.append(
            f'<a href="{href}" class="step-item">'
            f'<span class="step-icon exec">{num}</span> {html_mod.escape(label)}</a>'
        )
    parts.append('</div>')

    if not executive_only:
        parts.append('<div class="step-list-section">')
        parts.append('<div class="step-list-section-title">Technical Appendix</div>')
        for letter, href, label in tech_items:
            parts.append(
                f'<a href="{href}" class="step-item">'
                f'<span class="step-icon tech">{letter}</span> {html_mod.escape(label)}</a>'
            )
        parts.append('</div>')

    return "\n    ".join(parts)


def _intersection_observer_js() -> str:
    """Return IntersectionObserver JS for sidebar scroll tracking."""
    return """<script>
(function() {
  const sections = document.querySelectorAll('.detail-panel section, .detail-panel details');
  const navLinks = document.querySelectorAll('.step-item');
  const observer = new IntersectionObserver(entries => {
    entries.forEach(entry => {
      if (entry.isIntersecting) {
        const id = entry.target.id;
        navLinks.forEach(link => {
          link.classList.toggle('active', link.getAttribute('href') === '#' + id);
        });
      }
    });
  }, { root: document.querySelector('.detail-panel'), threshold: 0.2 });
  sections.forEach(s => { if (s.id) observer.observe(s); });
})();
</script>"""
