"""Report assembler — combines executive summary + appendix into a self-contained HTML file (v2).

One public function: ``assemble_report()``.
"""

from __future__ import annotations

import html as html_mod
from datetime import datetime, timezone

from wxcli.migration.report.executive import generate_executive_summary, _total_object_count
from wxcli.migration.report.appendix import generate_appendix
from wxcli.migration.report.score import compute_complexity_score
from wxcli.migration.report.styles import REPORT_CSS, GOOGLE_FONTS_LINKS
from wxcli.migration.store import MigrationStore


def assemble_report(
    store: MigrationStore,
    brand: str,
    prepared_by: str,
    cluster_name: str = "",
    cucm_version: str = "",
    executive_only: bool = False,
) -> str:
    """Assemble a complete, self-contained HTML assessment report.

    Args:
        store: Populated MigrationStore (post-analyze state).
        brand: Customer/brand name for the report header.
        prepared_by: Name of the SE/engineer who prepared the report.
        cluster_name: CUCM cluster name (optional).
        cucm_version: CUCM version string (optional).
        executive_only: If True, skip the technical appendix.

    Returns:
        Complete HTML document string (starts with ``<!DOCTYPE html>``).
    """
    safe_brand = html_mod.escape(brand)
    safe_prepared_by = html_mod.escape(prepared_by)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Compute summary stats for the summary bar
    score_result = compute_complexity_score(store)
    user_count = store.count_by_type("user")
    device_count = len(store.get_objects("device"))
    location_count = store.count_by_type("location")

    # Generate executive summary HTML
    executive_html = generate_executive_summary(
        store,
        brand=brand,
        prepared_by=prepared_by,
        cluster_name=cluster_name,
        cucm_version=cucm_version,
    )

    # Generate appendix HTML (unless executive_only)
    appendix_html = ""
    interstitial_html = ""
    if not executive_only:
        appendix_html = generate_appendix(store)
        interstitial_html = (
            '<div class="tech-interstitial">TECHNICAL REFERENCE</div>'
        )

    # Build sidebar nav
    sidebar_nav = _build_sidebar_nav(executive_only)

    # Summary bar
    summary_bar = (
        f'<div class="summary-bar">'
        f'<div class="summary-stat"><span class="value">{score_result.score}</span>'
        f'<span class="label">Score</span></div>'
        f'<div class="summary-stat"><span class="value">{user_count}</span>'
        f'<span class="label">Users</span></div>'
        f'<div class="summary-stat"><span class="value">{device_count}</span>'
        f'<span class="label">Devices</span></div>'
        f'<div class="summary-stat"><span class="value">{location_count}</span>'
        f'<span class="label">Sites</span></div>'
        f'</div>'
    )

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CUCM Migration Assessment — {safe_brand}</title>
  {GOOGLE_FONTS_LINKS}
  <style>{REPORT_CSS}</style>
</head>
<body>
  <!-- Sidebar navigation -->
  <aside class="sidebar">
    <div class="sidebar-header">
      <div class="sidebar-kicker">Migration Assessment</div>
      <div class="sidebar-brand">{safe_brand}</div>
      <div class="sidebar-meta">Prepared by {safe_prepared_by} &middot; {date_str}</div>
    </div>
    {sidebar_nav}
  </aside>

  <!-- Summary bar -->
  {summary_bar}

  <!-- Print header (hidden on screen) -->
  <div class="print-header">
    <h1>CUCM Migration Assessment</h1>
    <p class="brand">{safe_brand}</p>
    <p class="meta">Prepared by {safe_prepared_by} | {date_str}</p>
  </div>

  <!-- Main content -->
  <div class="detail-panel">
    <div class="detail-panel-content">
      <div class="content-card">
      {executive_html}
      {interstitial_html}
      {appendix_html}
      </div>
    </div>
  </div>

  <footer class="report-footer" style="margin-left:260px;">
    <p>Generated by cucm-assess | {date_str}</p>
  </footer>
</body>
</html>"""


def _build_sidebar_nav(executive_only: bool) -> str:
    """Build the sidebar navigation HTML."""
    nav_items = [
        '<nav>',
        '<div class="nav-label">Executive Summary</div>',
        '<a href="#score"><span class="nav-dot exec"></span> The Verdict</a>',
        '<a href="#inventory"><span class="nav-dot exec"></span> Your Environment</a>',
        '<a href="#scope"><span class="nav-dot exec"></span> Migration Scope</a>',
        '<a href="#next-steps"><span class="nav-dot exec"></span> Next Steps</a>',
    ]

    if not executive_only:
        nav_items.extend([
            '<div class="nav-divider"></div>',
            '<div class="nav-label">Technical Reference</div>',
            '<a href="#people"><span class="nav-dot tech"></span> People</a>',
            '<a href="#devices"><span class="nav-dot tech"></span> Devices</a>',
            '<a href="#features"><span class="nav-dot tech"></span> Call Features</a>',
            '<a href="#routing"><span class="nav-dot tech"></span> Routing</a>',
            '<a href="#gateways"><span class="nav-dot tech"></span> Gateways</a>',
            '<a href="#decisions"><span class="nav-dot tech"></span> Decisions</a>',
            '<a href="#data-quality"><span class="nav-dot tech"></span> Data Quality</a>',
        ])

    nav_items.append('</nav>')
    return "\n    ".join(nav_items)
