"""Report assembler — combines executive summary + appendix into a self-contained HTML file.

One public function: ``assemble_report()``.
"""

from __future__ import annotations

import html as html_mod
from datetime import datetime, timezone

from wxcli.migration.report.executive import generate_executive_summary
from wxcli.migration.report.appendix import generate_appendix
from wxcli.migration.report.styles import REPORT_CSS
from wxcli.migration.store import MigrationStore


def assemble_report(
    store: MigrationStore,
    brand: str,
    prepared_by: str,
    cluster_name: str = "",
    cucm_version: str = "",
    executive_only: bool = False,
) -> str:
    """Assemble a complete, self-contained HTML assessment report.

    Args:
        store: Populated MigrationStore (post-analyze state).
        brand: Customer/brand name for the report header.
        prepared_by: Name of the SE/engineer who prepared the report.
        cluster_name: CUCM cluster name (optional).
        cucm_version: CUCM version string (optional).
        executive_only: If True, skip the technical appendix.

    Returns:
        Complete HTML document string (starts with ``<!DOCTYPE html>``).
    """
    safe_brand = html_mod.escape(brand)
    safe_prepared_by = html_mod.escape(prepared_by)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    # Generate executive summary HTML
    executive_html = generate_executive_summary(
        store,
        brand=brand,
        prepared_by=prepared_by,
        cluster_name=cluster_name,
        cucm_version=cucm_version,
    )

    # Generate appendix HTML (unless executive_only)
    appendix_html = ""
    if not executive_only:
        appendix_html = generate_appendix(store)

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CUCM Migration Assessment — {safe_brand}</title>
  <style>{REPORT_CSS}</style>
</head>
<body>
  <header class="report-header">
    <h1>CUCM Migration Assessment</h1>
    <p class="brand">{safe_brand}</p>
    <p class="meta">Prepared by {safe_prepared_by} | {date_str}</p>
  </header>
  <main>
    {executive_html}
    {appendix_html}
  </main>
  <footer class="report-footer">
    <p>Generated by cucm-assess</p>
  </footer>
</body>
</html>"""
